$ANSIBLE_VAULT;1.1;AES256
38346339353435353866653538623464643135313831663733656130323361653236663361376536
3562393963376137353765656332613536643834636139310a626364646162343864383864383635
64396666326532373333343761653635623431656335393864643335326565663032636430353338
3761346131656261650a356530376431323865663938623030616637353530383830643734333562
39303364316130323261356461613266636139383933363732613130386235363565396662623738
65336634613133353939343230306332363931303132376535333366643636323331376261333363
35353565336231363736353262653430373730633236346636356132333236336461633535363134
39396364323736323831343665323362623265643262336630616565373735313338613864643562
34656138363561366465626665643531323530313531656163626661333066343230373934663332
34313062323566363434666438646233303263333937393830306630653163663037353636653433
36363439323962343938653832616566386134626563363538386464663533323233356463366665
63393336383338386666396532626465386335346562663064313739643939353464376139323334
65623735346465613066636331623733333963366462643437633039323838386232633337663763
62393061343230623731353564653838623936343466356363633032333564636133366630323530
34363464663063663065623338653563616164383030393233633033613861343435396364343431
33653230333732646330
