$ANSIBLE_VAULT;1.1;AES256
39343865613862393233653861396232656332616665333131326361613766336461383232663262
3439373533616433383138323763626564396334393565640a353630306530343765636163333239
64323966323534303330623762653538666239363438653466353835666230666364636130623934
3966303161663233630a303637326139626638323035656263663336366133343338633864386231
61303536333866663663383234303737616432626663636265386336386361633234613837396534
66653332636133356636336432376635393965323635646530326362363236643133356232393962
38313535333230313364316434336162643465386337363762623964386566616130653865373236
38393161643264316166666663653637373335353833663633333534616135333562383761336335
65303233346631633032336330626330663333623438343430656263623332333035343834613066
36326364656362313864326430306434633563333933376439663036653161303361663262636461
33346538303464626632623862363663316632343866303562333038336664306238613336623163
65653636396134626263643763666431363535383761356632663235646630303835306531356262
66303833333237393837326439326238643936623831336666666438623761333138353463613536
32326566613635326239383965366230636430396163363732313962303861333363613661393735
33623365646633396466343064326430646163373336643036616430393036383434636632346638
31386235623538626537
