apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-db
  namespace: coder
spec:
  instances: 3 

  storage:
    size: 5Gi
    storageClass: rook-ceph-block 

  bootstrap:
    initdb:
      database: coder_db
      owner: coder_user  # CNPG will automatically generate a secret for this user

  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  monitoring:
    enablePodMonitor: true

