apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: coder-db
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-secret-store 
  target:
    name: postgres-db-app 
    creationPolicy: Merge
    template:
      data:
        password: "{{ .dbpassword }}"

  data:
  - secretKey: dbpassword
    remoteRef:
      key: coder-database
      # property: password1111

