apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: coder-db
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-secret-store 
  target:
    name: postgres-db-app 
    creationPolicy: Merge
    template:
      data:
        password: "{{ .dbpassword | b64dec }}"
        pgpass: "postgres-db-rw:5432:coder_db:coder_user:{{ .dbpassword | b64dec }}"
        jdbc-uri: "jdbc:postgresql://postgres-db-rw.coder:5432/coder_db?password={{ .dbpassword | b64dec }}&user=coder_user"
        uri: "postgresql://coder_user:{{ .dbpassword | b64dec }}@postgres-db-rw.coder:5432/coder_db"
        # Add other templated fields as needed, e.g., fqdn variants

  data:
  - secretKey: dbpassword
    remoteRef:
      key: coder-db-password
      # property: password1111

