apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: coder-db
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: SecretStore
    name: oracle-secret-store # Must match SecretStore on the cluster
  target:
    name: coder-database-secret # Name for the secret on the cluster
    creationPolicy: Owner
  data:
  - secretKey: key
    remoteRef:
      key: coder-database

