apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-db
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-secret-store 
  target:
    name: postgres-db-appa
    creationPolicy: Owner
    # template:
    #   data:
    #     password: "{{ .dbpassword }}"
    #     pgpass: "postgres-db-rw:5432:coder_db:coder_user:{{ .dbpassword }}"
    #     jdbc-uri: "jdbc:postgresql://postgres-db-rw.coder:5432/coder_db?password={{ .dbpassword }}&user=coder_user"
    #     uri: "postgresql://coder_user:{{ .dbpassword }}@postgres-db-rw.coder:5432/coder_db"

  data:
  - secretKey: dbpassword
    remoteRef:
      key: coder-db-password
      # decodingStrategy: Base64URL
      # property: password1111

