---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder 
  namespace: coder 
spec:
  interval: 1h
  releaseName: coder
  targetNamespace: coder 
  values:
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: postgres-db-app   
              key: uri
  chart:
    spec:
      chart: coder
      version: "2.29.0" 
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: coder
