---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder 
  namespace: coder 
spec:
  interval: 1h
  releaseName: coder
  targetNamespace: coder 
  values:
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: postgres-db-app   
              key: uri
        - name: CODER_WILDCARD_ACCESS_URL
          value: "*-coder.pikaa.cc"
        - name: CODER_ACCESS_URL
          value: "https://coder.pikaa.cc"
      ingress:
        enable: true
        className: nginx
        host: "coder.pikaa.cc"
        tls:
          enable: true
          secretName: coder-tls-secret
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt"
  chart:
    spec:
      chart: coder
      version: "2.29.0" 
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: coder
