# oci-user-principal-secretstore.yaml 
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: oracle-secret
  namespace: external-secrets # Use the namespace where ESO is installed
spec:
  provider:
    oracle:
      # Replace with the OCID of your specific OCI Vault
      vault: ocid1.vault.oc1.ap-singapore-1.gzutjgmjaacl2.abzwsljrzed7iv6bbslg7hvyxkqvpzpjcxjkbfi24al7anae2fuudekw6kpa
      # Use UserPrincipal for local clusters
      principalType: UserPrincipal 
      auth:
        tenancy:
          secretRef:
            name: oci-api-credentials
            key: tenancy
        user:
          secretRef:
            name: oci-api-credentials
            key: user
        fingerprint:
          secretRef:
            name: oci-api-credentials
            key: fingerprint
        privatekey:
          secretRef:
            name: oci-api-credentials
            key: privatekey
        region:
          secretRef:
            name: oci-api-credentials
            key: region
