apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oracle-secret-store
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.ap-singapore-1.gzutjgmjaacl2.abzwsljrzed7iv6bbslg7hvyxkqvpzpjcxjkbfi24al7anae2fuudekw6kpa
      region: ap-singapore-1
      auth:
        user: ocid1.user.oc1..aaaaaaaacg4347yynchvgho3fn3zazybn5mqauwc32du6q2zqyi5jmaiqkgq
        tenancy: ocid1.tenancy.oc1..aaaaaaaam3t5ds2sljryfh4fgqbgzkqj6mjukx6adi6o3t2nwb5tmlkfscda
        secretRef:
          fingerprint:
              name: oracle-secret
              key: fingerprint
              namespace: external-secrets
          privatekey:
              name: oracle-secret
              key: privatekey
              namespace: external-secrets


