apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nginx_ingress/namespace.yaml
  - ./nginx_ingress/helm_release.yaml
  - ./metallb/helm_release.yaml
  - ./metallb/namespace.yaml
  - ./metallb/ip_address_pool.yaml
