# metallb-repo.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system # Or the namespace where your source-controller runs
spec:
  interval: 30m
  url: https://metallb.github.io/metallb
  timeout: 3m
