$ANSIBLE_VAULT;1.1;AES256
36313266656261373735376462366462306631333937646535613865366130373238353535313434
3264623461633162633562326365326134303735333532610a326234653930393961316431313361
64323136303137333134353062373365326533623834353661353266666230343132356363346235
6633643634653334610a656661383061353736306539653461663463373030363464373034646238
33643064363839363535373331326633326539383837626361616439616263376263636133306335
37346334633365346362376539386139306334633562343361316430373033313166366138393361
353130323165323363653061373638323530
