$ANSIBLE_VAULT;1.1;AES256
34376637633139346561613661623231653334336238396262316363626131656263633839383464
6338623230623461373862313139616334633331356363320a383034653063313233623935633333
35643033393463306632306361343137376339626364313134356236653866306435323763303335
6533366262366439330a393632303563363463383565323837653438303765616435316533303633
64373031353535653634646430333464356634353338653061346634343838343737306530376663
34656134303163643162653930663538666531343036623735613963363066666633643561363363
666364383633323865663738396238313466
