$ANSIBLE_VAULT;1.1;AES256
31326131383830626539306565326462373163336265623832353639343662653861306366343931
6136313936363361356433396165343631313864303039340a653531326535323264633666376130
66316437643135373831626630393031643663656635343035336366666265393435323838333238
6635373030303131360a653530663566303534653462353739636466636330613234373938643065
35626139333034663034373137333364346562613165386338613664303434616663386439333661
61333233393639346564363766396336326134376337313133343331623331376135643739373164
396164616532373835643334333166383763
